[2025-06-27T05:41:03.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T05:41:03.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [queued]>
[2025-06-27T05:41:04.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [queued]>
[2025-06-27T05:41:04.013+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T05:41:04.119+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-06-27 04:41:00+00:00
[2025-06-27T05:41:04.127+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T05:41:04.130+0000] {standard_task_runner.py:63} INFO - Started process 74 to run task
[2025-06-27T05:41:04.129+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN', 'run_hop_pipeline', 'scheduled__2025-06-27T04:41:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main.py', '--cfg-path', '/tmp/tmpu3oeqmdm']
[2025-06-27T05:41:04.131+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask run_hop_pipeline
[2025-06-27T05:41:04.232+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [running]> on host 760ca3d6cb03
[2025-06-27T05:41:04.407+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T04:41:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-27T04:41:00+00:00'
[2025-06-27T05:41:04.408+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T05:41:04.541+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T05:41:04.556+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T05:41:04.556+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /opt/airflow/ProyectoSmartMed")
[2025-06-27T05:41:04.571+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN, task_id=run_hop_pipeline, run_id=scheduled__2025-06-27T04:41:00+00:00, execution_date=20250627T044100, start_date=20250627T054103, end_date=20250627T054104
[2025-06-27T05:41:04.589+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /opt/airflow/ProyectoSmartMed"); 74)
[2025-06-27T05:41:04.627+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T05:41:04.660+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T05:41:04.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T06:06:12.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:06:12.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [queued]>
[2025-06-27T06:06:12.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [queued]>
[2025-06-27T06:06:12.704+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T06:06:12.736+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-06-27 04:41:00+00:00
[2025-06-27T06:06:12.752+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:06:12.755+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN', 'run_hop_pipeline', 'scheduled__2025-06-27T04:41:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main.py', '--cfg-path', '/tmp/tmpnyi7by2y']
[2025-06-27T06:06:12.758+0000] {standard_task_runner.py:63} INFO - Started process 66 to run task
[2025-06-27T06:06:12.758+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_hop_pipeline
[2025-06-27T06:06:12.910+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [running]> on host 71fa9c4e435e
[2025-06-27T06:06:13.067+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T04:41:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-27T04:41:00+00:00'
[2025-06-27T06:06:13.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:06:13.211+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T06:06:13.237+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T06:06:16.701+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T06:06:16.702+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - Running the entrypoint script with PID 7
[2025-06-27T06:06:16.704+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - The specified project folder exists
[2025-06-27T06:06:16.705+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - Registering project ProyectoSmartMed in the Hop container configuration
[2025-06-27T06:06:16.707+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T06:11:13.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:11:13.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [queued]>
[2025-06-27T06:11:13.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [queued]>
[2025-06-27T06:11:13.262+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T06:11:13.288+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-06-27 04:41:00+00:00
[2025-06-27T06:11:13.306+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:11:13.310+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2025-06-27T06:11:13.311+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN', 'run_hop_pipeline', 'scheduled__2025-06-27T04:41:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main.py', '--cfg-path', '/tmp/tmph9c8j1we']
[2025-06-27T06:11:13.314+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_hop_pipeline
[2025-06-27T06:11:13.491+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN.run_hop_pipeline scheduled__2025-06-27T04:41:00+00:00 [running]> on host 9bc187bed6c8
[2025-06-27T06:11:13.672+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T04:41:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-27T04:41:00+00:00'
[2025-06-27T06:11:13.674+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:11:13.975+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T06:11:14.014+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T06:11:16.244+0000] {docker.py:436} INFO - 2025/06/27 06:11:16 - Running the entrypoint script with PID 6
[2025-06-27T06:11:16.249+0000] {docker.py:436} INFO - 2025/06/27 06:11:16 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T06:11:16.284+0000] {docker.py:436} INFO - 2025/06/27 06:11:16 - The specified project folder exists
[2025-06-27T06:11:16.295+0000] {docker.py:436} INFO - 2025/06/27 06:11:16 - Registering project ProyectoSmartMed in the Hop container configuration
[2025-06-27T06:11:16.305+0000] {docker.py:436} INFO - 2025/06/27 06:11:16 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T06:38:34.324+0000] {local_task_job_runner.py:214} ERROR - Heartbeat time limit exceeded!
[2025-06-27T06:38:35.930+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
